# Generated by Django 4.2.1 on 2023-05-17 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='position',
            field=models.CharField(default='Question', max_length=128),
            preserve_default=False,
        ),
    ]
